[build-system]
requires = [
    "setuptools >= 44",
    "wheel >= 0.30",
    "setuptools_scm[toml]>=3.4",
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 120

[tool.setuptools_scm]
write_to = "src/pytest_print/version.py"
write_to_template = """
\"\"\" Version information \"\"\"
from __future__ import unicode_literals

__version__ = "{version}"
"""
